name: divergent
description: Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  animated_splash: ^1.0.0
  colornames: ^0.1.0
  cupertino_icons: ^1.0.5
  english_words: ^4.0.0
  flutter:
    sdk: flutter
  flutter_icons: ^1.1.0
  flutter_tts: ^3.6.3
  fluttertoast: ^8.2.1
  geolocator: ^9.0.2
  hexcolor: ^3.0.1
  http: ^0.13.5
  image_picker: ^0.8.7+3
  path: ^1.8.2
  path_provider: ^2.0.14
  percent_indicator: ^4.2.3
  shake: ^2.2.0
  shared_preferences: ^2.1.0
  simple_ocr_plugin: ^0.1.1
  splashscreen: ^1.3.5
  telephony: ^0.2.0
  # tflite: ^1.1.2
  vibration: ^1.7.6

dev_dependencies:
  camera: ^0.10.4
  flutter_launcher_icons: ^0.13.0
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
  assets:
    - assets/ssd_mobilenet.tflite
    - assets/ssd_mobilenet.txt
    - assets/cash_model_unquant.tflite
    - assets/cash_labels.txt
    - assets/icon.jpg
    - assets/icon-circle.png
    - assets/tflite/labels.txt
    - assets/tflite/model_unquant.tflite
    - assets/images/splashScreen.png
    - assets/images/appIcon.png
    - assets/images/deaf_image.png
    - assets/images/colour_blind_image.png
    - assets/images/blind_image.png
flutter_icons:
  image_path: "assets/icon.jpg"
  android: true
  ios: true
